from django.contrib import admin
from .models import *

admin.site.register(Genero)
admin.site.register(Consola)
admin.site.register(Producto)
admin.site.register(Rol)
admin.site.register(Empleado)
admin.site.register(Comuna)
admin.site.register(Direccion)
admin.site.register(Cliente)
admin.site.register(DetalleVenta)
admin.site.register(MetodoPago)
admin.site.register(EstadoVenta)
admin.site.register(Venta)
admin.site.register(Sucursal)
admin.site.register(Bodega)
admin.site.register(Detalle_bodega)
admin.site.register(Guia_despacho)
admin.site.register(Guia_despacho_detalle)
admin.site.register(Region)
admin.site.register(Pasillo)
admin.site.register(Ubicacion_producto)
admin.site.register(Seccion)