# Generated by Django 4.2.1 on 2023-05-13 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_detalle_bodega_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('idPasillo', models.AutoField(primary_key=True, serialize=False)),
                ('numeroPasillo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('idSeccion', models.AutoField(primary_key=True, serialize=False)),
                ('letraSeccion', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='detalle_bodega',
            name='cantidadProd',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Ubicacion_producto',
            fields=[
                ('idUbicacion', models.AutoField(primary_key=True, serialize=False)),
                ('pasillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.pasillo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.seccion')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_bodega',
            name='ubicacion_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.ubicacion_producto'),
            preserve_default=False,
        ),
    ]
